services:
    marcovo.mathjax.listener:
        class: marcovo\mathjax\event\listener
        arguments:
            - @user
            - @template
            - @config
        tags:
            - { name: event.listener }
